version: "3"
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/RoomEase
    ports:
      - "3000:3000"
      - "27017:27017"
      - "8080:8080"
    command: /bin/bash
