name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.19.0]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for merging full history
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 14.19.0
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.0
      - run: npm install
      - run: rm -rf public

  auto_update_non_main_branches:
    needs: deploy # Only run after a successful deployment to main
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Merge and Push to Krish
        run: |
          git checkout Krish
          git merge --no-ff main
          git push origin HEAD:Krish # Explicitly specify the local HEAD to the remote Krish branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge and Push to Carter
        run: |
          git checkout Carter
          git merge --no-ff main
          git push origin HEAD:Carter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge and Push to John
        run: |
          git checkout John
          git merge --no-ff main
          git push origin HEAD:John
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge and Push to Ishan
        run: |
          git checkout Ishan
          git merge --no-ff main
          git push origin HEAD:Ishan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge and Push to Will
        run: |
          git checkout Will
          git merge --no-ff main
          git push origin HEAD:Will
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge and Push to Nathan
        run: |
          git checkout Nathan
          git merge --no-ff main
          git push origin HEAD:Nathan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
