name: CI

permissions:
  contents: write   # allow pushes from the workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        node-version: [14.19.0]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
      - name: Use Node.js 14.19.0
        uses: actions/setup-node@v3
        with:
          node-version: 14.19.0
      - run: npm install
      - run: rm -rf public

  update-branches:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        branch: [Krish, Carter, John, Ishan, Will, Nathan]
    name: auto_update_${{ matrix.branch }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Set Git identity
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Merge main into ${{ matrix.branch }}
        run: |
          git checkout ${{ matrix.branch }}
          git merge --no-ff main || true

      - name: Push if no conflicts
        run: |
          conflicts=$(git diff --name-only --diff-filter=U)
          if [ -z "$conflicts" ]; then
            echo "✅ No conflicts in ${{ matrix.branch }}, pushing…"
            git push origin HEAD:${{ matrix.branch }}
          else
            echo "⚠️ Conflicts detected in ${{ matrix.branch }} – skipping push"
            git merge --abort
          fi
